# Generated by Django 2.2.1 on 2019-06-14 00:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('player_position', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerSeason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.PositiveIntegerField(default=2019, validators=[django.core.validators.MinValueValidator(1920), django.core.validators.MaxValueValidator(2019)])),
                ('games_played', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(16)])),
                ('games_started', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(16)])),
                ('pass_completions', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('pass_attempts', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('passing_yards', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('touchdowns', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('interceptions', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('passer_rating', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apr8_web.Player')),
            ],
        ),
    ]
